/// OtaEvent
class OtaEvent {
  ///Constructor for OtaEvent
  OtaEvent(this.status, this.value);

  /// Current status as enum value
  OtaStatus status;

  /// Additional status info e.g. percents downloaded or error message (can be null)
  String? value;
}

/// Enum values describing states
enum OtaStatus {
  /// FILE IS BEING DOWNLOADED
  DOWNLOADING,

  /// INSTALLATION HAS BEEN TRIGGERED
  INSTALLING,

  /// INSTALLATION HAS BEEN SUCCESSFULY DONE
  INSTALLATION_DONE,

  /// DOWNLOAD IS ALREADY RUNNING
  ALREADY_RUNNING_ERROR,

  /// INSTALLATION WAS NOT SUCCESSFULL
  INSTALLATION_ERROR,

  /// COULD NOT CONTINUE BECAUSE OF MISSING PERMISSIONS
  PERMISSION_NOT_GRANTED_ERROR,

  /// UNKWNON ERROR. SEE VALUE FOR MORE INFROMATION
  INTERNAL_ERROR,

  /// FILE COULD NOT BE DOWNLOADED. SEE VALUE FOR MORE INFORMATION
  DOWNLOAD_ERROR,

  /// CHECKSUM VERIFICATION FAILED. MOSTLY THIS IS DUE INCORRECT OR CORRUPTED FILE
  /// THIS IS ALSO RETURNED IF PLUGIN WAS UNABLE TO CALCULATE SHA 256 HASH OF DOWNLOADED FILE
  /// SEE VALUE FOR MORE INFORMATION
  CHECKSUM_ERROR,

  /// DOWNLOAD WAS CANCELED
  CANCELED,
}

/// EXCEPTION FOR QUICK IDENTIFICATION OF ERRORS THROWN FROM THIS PLUGIN.
/// THIS IS USED CURRENTLY ONLY FOR INPUT PARAMETER VERIFICATION ERRORS. IF THERE IS PROBLEM WITH
/// DOWNLOADING THE FILE OR RUNNING UPDATE OtaEvent WITH ONE OF THE _ERROR STATUSES IS USED
class OtaUpdateException implements Exception {
  /// DEFAULT CONSTRUCTOR
  OtaUpdateException(this.message);

  /// ERROR MESSAGE
  final String message;

  @override
  String toString() {
    return 'Exception: $message';
  }
}
